version: '2'

services:
  reverseproxy:
    depends_on:
      - nginx_web
    build: ./reverseproxy
    ports:
      - 80:80
    restart: always
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf

  nginx_web:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/public:/var/www/html
      - ./nginx/conf/site.conf:/etc/nginx/conf.d/site.conf

  php7:
    build: ./php-7
    restart: always
    volumes:
      - ./nginx/public:/var/www/html
      - ./php-7/conf/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass